CallBoard/CallBoard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path('calls/', include('calls.urls')),
    path('profile/', include('profil.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CallBoard/calls/urls.py
from django.urls import path
from .views import CallsList, CallCreate, CallUpdate, CallDelete, MyCallsList, RespondSend, MyRespondList,\
   respond_accept_yes, respond_accept_no


urlpatterns = [
   path('', CallsList.as_view(), name='call_list'),
   path('my/', MyCallsList.as_view(), name='my_call_list'),
   path('<int:pk>', RespondSend.as_view(), name='respond_send'),
   path('accept/<int:pk>/', respond_accept_yes, name='respond_accept_yes'),
   path('reject/<int:pk>/', respond_accept_no, name='respond_accept_no'),
   path('create/', CallCreate.as_view(), name='call_create'),
   path('<int:pk>/edit/', CallUpdate.as_view(), name='call_edit'),
   path('<int:pk>/delete/', CallDelete.as_view(), name='call_delete'),
   path('my/responds/', MyRespondList.as_view(), name='my_respond_list'),
]

CallBoard/calls/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from PIL import Image


class Call(models.Model):
    """ Объявления. """
    CATEGORIES_LIST = [
        ('tanks', 'Танки'),
        ('hills', 'Хилы'),
        ('dd', 'ДД'),
        ('traders', 'Торговцы'),
        ('gild_masters', 'Гилдмастеры'),
        ('quest_givers', 'Квестгиверы'),
        ('blacksmiths', 'Кузнецы'),
        ('tanners', 'Кожевники'),
        ('potion_masters', 'Зельевары'),
        ('spell_masters', 'Мастера заклинаний'),
    ]
    call_author = models.ForeignKey(User, on_delete=models.CASCADE)
    call_create_date = models.DateTimeField(auto_now_add=True)
    call_category = models.CharField(max_length=14, choices=CATEGORIES_LIST, default='tanks')
    call_header = models.CharField(max_length=128)
    call_text = models.TextField()
    call_img = models.ImageField(upload_to='call', null=True, blank=True, verbose_name='Изображение')

    def __str__(self):
        return f"Объявление от {self.call_create_date:%d.%m.%Y %H:%M} (запись №{self.id})"

    def get_absolute_url(self):
        return reverse('respond_send', args=[str(self.id)])

    def save(self):
        super().save()
        if self.call_img:
            img = Image.open(self.call_img.path)
            if img.height > 300 or img.width > 300:
                output_size = (300, 300)
                img.thumbnail(output_size)
                img.save(self.call_img.path)


class Respond(models.Model):
    """ Отклики к объявлениям. """
    respond_call = models.ForeignKey(Call, on_delete=models.CASCADE)
    respond_author = models.ForeignKey(User, on_delete=models.CASCADE)
    respond_text = models.TextField()
    respond_create_date = models.DateTimeField(auto_now_add=True)
    respond_accept = models.BooleanField(null=True)

    def __str__(self):
        return f'{self.respond_call} {self.respond_text}'

CallBoard/calls/forms.py
from django import forms
from .models import Call, Respond


class CallForm(forms.ModelForm):
    class Meta:
        model = Call
        fields = [
            'call_category',
            'call_header',
            'call_text',
            'call_img',
        ]


class RespondForm(forms.ModelForm):
    class Meta:
        model = Respond
        fields = [
            'respond_text',
        ]

CallBoard/calls/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import (
    ListView, DetailView, CreateView, UpdateView, DeleteView
)

from .models import Call, Respond
from .filters import CallFilter, CallFilterForResponds
from .forms import CallForm, RespondForm


class CallsList(ListView):
    """Все объявления"""
    model = Call
    ordering = '-call_create_date'
    template_name = 'calls.html'
    context_object_name = 'calls'
    paginate_by = 8

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = CallFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filterset'] = self.filterset
        return context


class CallCreate(LoginRequiredMixin, CreateView):
    """Создание объявления"""
    raise_exception = True
    form_class = CallForm
    model = Call
    template_name = 'call_create.html'

    def form_valid(self, form):
        form.instance.call_author = self.request.user
        return super().form_valid(form)


class CallUpdate(LoginRequiredMixin, UpdateView):
    """Редактирование объявления"""
    raise_exception = True
    form_class = CallForm
    model = Call
    template_name = 'call_edit.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Признак объявления пользователя для защиты от редактирования другими пользователями
        context['is_my_call'] = Call.objects.get(id=self.kwargs['pk']).call_author == self.request.user
        return context


class CallDelete(LoginRequiredMixin, DeleteView):
    """Удаление объявления"""
    raise_exception = True
    model = Call
    template_name = 'call_delete.html'
    success_url = reverse_lazy('call_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Признак объявления пользователя для защиты от удаления другими пользователями
        context['is_my_call'] = Call.objects.get(id=self.kwargs['pk']).call_author == self.request.user
        return context


class MyCallsList(ListView):
    """Список объявлений пользователя"""
    model = Call
    template_name = 'my_calls.html'
    context_object_name = 'calls'
    paginate_by = 8

    def get_queryset(self):
        queryset = Call.objects.filter(call_author=self.request.user.id).order_by('-call_create_date')
        self.filterset = CallFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filterset'] = self.filterset
        return context


class RespondSend(LoginRequiredMixin, CreateView):
    """Просмотр объявления + создание отклика"""
    raise_exception = True
    form_class = RespondForm
    model = Respond
    template_name = 'respond.html'

    def form_valid(self, form):
        form.instance.respond_author = self.request.user
        form.instance.respond_call = Call.objects.get(id=self.kwargs['pk'])
        return super().form_valid(form)

    def get_success_url(self):
        return '/calls/'+ str(self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['call'] = Call.objects.get(id=self.kwargs['pk'])
        # Получаем все принятые отклики на текущее объявление, за исключением авторских
        context['responds'] = Respond.objects.filter(respond_call=Call.objects.get(id=self.kwargs['pk'])).exclude(
            respond_author=self.request.user).filter(respond_accept=True)
        # Получаем все авторские отклики без исключений
        context['my_responds'] = Respond.objects.filter(respond_call=Call.objects.get(id=self.kwargs['pk'])).filter(
            respond_author=self.request.user)
        # Получаем все отклики кроме авторских, кроме непринятых
        context['my_responds_edit'] = Respond.objects.filter(
            respond_call=Call.objects.get(id=self.kwargs['pk'])).exclude(respond_accept=False)
        context['is_my_call'] = Call.objects.get(id=self.kwargs['pk']).call_author == self.request.user
        return context


class MyRespondList(LoginRequiredMixin, ListView):
    """Все отклики на объявления пользователя"""
    raise_exception = True
    model = Respond
    template_name = 'my_responds.html'
    context_object_name = 'responds'

    def get_queryset(self):
        queryset = Respond.objects.filter(respond_call__call_author_id=self.request.user.id).exclude(respond_accept=False)
        self.filterset = CallFilterForResponds(self.request.GET, queryset, request=self.request.user.id)
        if self.request.GET:
            return self.filterset.qs
        return Respond.objects.none()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filterset'] = self.filterset
        return context


def respond_accept_yes(request, pk):
    """Принятие отклика"""
    respond = Respond.objects.get(id=pk)
    respond.respond_accept = True
    respond.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def respond_accept_no(request, pk):
    """Отклонение отклика"""
    respond = Respond.objects.get(id=pk)
    respond.respond_accept = False
    respond.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

CallBoard/templates/call_create.html
{% extends 'flatpages/default.html' %}
{% load custom_tags %}

{% block content %}
    <br>
    <input type="button" value="Назад" onClick="history.back();">
    <br>
    <h1>Создание объявления</h1>
    <hr>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Сохранить" />
    </form>
{% endblock content %}

CallBoard/templates/call_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
    {% if is_my_call %}
        <br>
        <input type="button" value="Назад" onClick="history.back();">
        <br>
        <h1>Удаление объявления</h1>
        <hr>
        <form action="" method="post">
            {% csrf_token %}
            <p>Удаляем "{{ object.call_header }}"?</p>
            <input type="submit" value="Delete" />
        </form>
    {% else %}
        <br>
        <h2>Вы не можете удалить чужое объявление!</h2>
    {% endif %}
{% endblock content %}

CallBoard/templates/call_edit.html
{% extends 'flatpages/default.html' %}
{% load custom_tags %}

{% block content %}
    {% if is_my_call %}
        <br>
        <input type="button" value="Назад" onClick="history.back();">
        <br>
        <h1>Редактирование объявления</h1>
        <hr>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Save" />
        </form>
    {% else %}
        <br>
        <h2>Вы не можете редактировать чужое объявление!</h2>
    {% endif %}
{% endblock content %}

CallBoard/templates/calls.html
{% extends 'flatpages/default.html' %}
{% load custom_tags %}

{% block title %}
Объявления
{% endblock title %}

{% block content %}
    <br>
    <input type="button" value="Создать объявление" onClick='location.href="{% url 'call_create' %}"'>
    <br><br>
   <h1>Все объявления</h1>

   {# Добавляем форму, которая объединяет набор полей, которые будут отправляться в запросе #}
   <form action="" method="get">
       {# Переменная, которую мы передали через контекст, может сгенерировать нам форму с полями #}
       {{ filterset.form.as_p }}
       {# Добавим кнопку отправки данных формы #}
       <input type="submit" value="Найти" />
   </form>

   <hr>
   {% if calls %}
       <table>
           <tr>
               <td>Категория</td>
               <td>Дата публикации</td>
               <td>Заголовок</td>
               <td>Текст</td>
           </tr>

           {% for call in calls %}
           <tr>
               <td>{{ call.get_call_category_display }}</td>
               <td>{{ call.call_create_date|date:'d.m.Y' }}</td>
               <td><a href="{% url 'respond_send' call.id %}">{{ call.call_header|truncatewords:10 }}</a></td>
               <td><a href="{% url 'respond_send' call.id %}">{{ call.call_text|truncatewords:35 }}</a></td>
           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Объявлений нет!</h2>
   {% endif %}

   {% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

CallBoard/templates/my_calls.html
{% extends 'flatpages/default.html' %}
{% load custom_tags %}

{% block title %}
Объявления
{% endblock title %}

{% block content %}
    <br>
    <input type="button" value="Создать объявление" onClick='location.href="{% url 'call_create' %}"'>
    <br><br>
       <h1>Мои объявления</h1>
    <br>
   {# Добавляем форму, которая объединяет набор полей, которые будут отправляться в запросе #}
   <form action="" method="get">
       {# Переменная, которую мы передали через контекст, может сгенерировать нам форму с полями #}
       {{ filterset.form.as_p }}
       {# Добавим кнопку отправки данных формы #}
       <input type="submit" value="Найти" />
   </form>

   <hr>
   {% if calls %}
       <table>
           <tr>
               <td>Категория</td>
               <td>Дата публикации</td>
               <td>Заголовок</td>
               <td>Текст</td>
           </tr>

           {% for call in calls %}
           <tr>
               <td>{{ call.get_call_category_display }}</td>
               <td>{{ call.call_create_date|date:'d.m.Y' }}</td>
               <td><a href="{% url 'respond_send' call.id %}">{{ call.call_header|truncatewords:10 }}</a></td>
               <td><a href="{% url 'respond_send' call.id %}">{{ call.call_text|truncatewords:35 }}</a></td>
           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Объявлений нет!</h2>
   {% endif %}

   {% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

CallBoard/templates/my_responds.html
{% extends 'flatpages/default.html' %}
{% load custom_tags %}

{% block title %}
Отклики на мои объявления
{% endblock title %}

{% block content %}
   <h1>Отклики на мои объявления</h1>
   <form action="" method="get">
       {{ filterset.form.as_p }}
       <input type="submit" value="Применить фильтр" />
   </form>
   <hr>
   {% if responds %}
        {% for respond in responds %}
            <tr>
                <td>{{ respond.respond_author }}</td>
                <td>{{ respond.respond_create_date|date:'d.m.Y' }}</td>
                <td>{{ respond.respond_text }}</td>
                {% if not respond.respond_accept %}
                    <td><b><a style="color: green;" href="{% url 'respond_accept_yes' respond.id %}">Принять</a></b></td>
                    <td><b><a style="color: red;" href="{% url 'respond_accept_no' respond.id %}">Отклонить</a></b></td>
                {% else %}
                    <td><b style="color: green;"><i><u>Принят</u></i></b></td>
                {% endif %}
            </tr>
            <br>
        {% endfor %}
   {% else %}
       <h2>Откликов нет!</h2>
   {% endif %}

{% endblock content %}

CallBoard/templates/profile_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<br>
<input type="button" value="Назад к списку объявлений" onClick='location.href="http://127.0.0.1:8000/calls/"'>
<h1>Мой профиль</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

CallBoard/templates/respond.html
{% extends 'flatpages/default.html' %}

{% block title %}
Объявление
{% endblock title %}

{% block content %}
<br>
<input type="button" value="В список объявлений" onClick='location.href="http://127.0.0.1:8000/calls"'>
{% if is_my_call %}
    <input type="button" value="Редактировать" onClick='location.href="{% url 'call_edit' call.id %}"'>
    <input type="button" value="Удалить" onClick='location.href="{% url 'call_delete' call.id %}"'>
{% endif %}
<br>
<h4><br>{{ call.call_author }} {{ call.call_create_date|date:'d.m.Y' }} {{ call.get_call_category_display }}</h4>
<h2>{{ call.call_header }}</h2>
{% if call.call_img %}
    <img src="{{ call.call_img.url }}" />
{% endif %}
<h4><br>{{ call.call_text }}</h4>

{% if not is_my_call %}
    {% if my_responds %}
        <hr>
        <p style="color: green;"><b>Вы откликнулись на это объявление:</b></p>
        {% for respond in my_responds %}
            <tr>
                <td>{{ respond.respond_create_date|date:'d.m.Y' }}</td>
                <td>{{ respond.respond_text }}</td>
                {% if respond.respond_accept == None %}
                    <td><b style="color: gray;"><i><u>Не просмотрен</u></i></b></td>
                {% elif respond.respond_accept %}
                    <td><b style="color: green;"><i><u>Принят</u></i></b></td>
                {% else %}
                    <td><b style="color: red;"><i><u>Отклонен</u></i></b></td>
                {% endif %}
            </tr>
        {% endfor %}
    {% else %}
        <hr>
        <p style="color: gray;"><b>Вы не откликались на это объявление:</b></p>
        <form id="id" action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Отправить отклик" />
        </form>
    {% endif %}
    <hr>
    {% if responds %}
         <p style="color: blue;"><b>Отклики других пользователей</b></p>
        <hr>
        {% for respond in responds %}
            <tr>
                <td>{{ respond.respond_author }}</td>
                <td>{{ respond.respond_create_date|date:'d.m.Y' }}</td>
                <td>{{ respond.respond_text }}</td>
            </tr>
            <br>
        {% endfor %}
    {% else %}
        <p style="color: gray;"><b>Откликов других пользователей пока нет</b></p>
        <hr>
    {% endif %}
{% else %}
    <hr>
    {% if my_responds_edit %}
        <p style="color: blue;"><b>Отклики на ваше объявление</b></p>
        <hr>
        {% for respond in my_responds_edit %}
            <tr>
                <td>{{ respond.respond_author }}</td>
                <td>{{ respond.respond_create_date|date:'d.m.Y' }}</td>
                <td>{{ respond.respond_text }}</td>
                {% if not respond.respond_accept %}
                    <td><b><a style="color: green;" href="{% url 'respond_accept_yes' respond.id %}">Принять</a></b></td>
                    <td><b><a style="color: red;" href="{% url 'respond_accept_no' respond.id %}">Отклонить</a></b></td>
                {% else %}
                    <td><b style="color: green;"><i><u>Принят</u></i></b></td>
                {% endif %}
            </tr>
            <br>
        {% endfor %}
    {% else %}
        <p style="color: gray;"><b>Откликов пока нет</b></p>
        <hr>
    {% endif %}
{% endif %}
{% endblock content %}